### ISSUE TITLE
Query /list method not working anymore

### ISSUE THREAD

**Issue by Superjo149** [MCAPI-CA/Issues#1]
The query list feature doesn't seem to be working anymore. It's been a bit more than a week I think since it last worked.

![image](https://cloud.githubusercontent.com/assets/4314204/11614288/5c723f80-9c3e-11e5-91e3-022f516565bb.png)

**Comment by Yive** [comment]
I just checked against a random server from a server listing site. Seems to work perfectly fine. That server never had query enabled, I just put them as the url since I didn't know of any large server that used it.

```
{
  "Status": true,
  "Players": {
    "online": 3,
    "max": 50,
    "list":["Kevin16","LocutusvonBorg","_RiMi"]
  },
  "Version": "1.4.7"
}
```

I will add in a system that outputs an error if the server is offline or something fails, tomorrow. Forgot to do that.
