### ISSUE TITLE
[Suggestion] Caching of name-API doesn't affect the UUID API

### ISSUE THREAD

**Issue by games647** [MCAPI-CA/Issues#22]
I'm using the name-api endpoint.

name/uuid/<uuid>

There we receive the most recent username associated to the UUID. I found out that when I access this route first and then access the uuid route (uuid/player/games647), it seems to that the cache is re fetched, because the cache property is newer and current_time is missing. 

It might be helpful to cache it for boths, because all necessary data for the uuid-route (uuid/player/) is also present in the name-route (/name/uuid/<uuid>) too.

This would at least some requests to the mojang servers. What do you think about it?

**Comment by Yive** [comment]
Not 100% sure what you mean, but whatever I am about to type is probably along the same lines of what you mean.

I've been thinking of pairing the two together to avoid less rate limits + less ram being used due to having less cached data. I've already done that for the query part in the new system of MCAPI which hopefully comes out soon, so I'll expand it to the other APIs, will probably take a lot of load off of the CPU & such too.
