### ISSUE TITLE
[Question] Caching issue with my server only?!

### ISSUE THREAD

**Issue by darthdoesmc** [MCAPI-CA/Issues#29]
Hey there!

This is more of a question than a suggestion. I could not find an email address or Twitter so will just post it here.

On your website, it says everything is cached for a minute and I use your API in an external panel of mine to display a number of people online on my server. This requests every second. 
The link just shows some "cache" JSON, which is a bit weird. Is this is 1 minute cache because it has only started happening to me very recently.

`https://mcapi.ca/query/mc.darthdoesmc.net/players`

Am I doing anything wrong? I could not find any terms of service thing and I hope I have not been blocked. If there's anything you wish me to change I will be more than happy to do so,

- Darth

**Comment by darthdoesmc** [comment]
It works now, but I am still confused on the cache time. Could you clarify this?

**Comment by Yive** [comment]
The cache times on the front page of the website are very outdated. Queries used to be cached for one minute due to abuse, but I've managed to get it down to roughly around 30 seconds of caching time.

The server was being overloaded as you can see here:
`Status: "Processes active: 800, idle: 0, Requests: 1502514060, slow: 0, Traffic: 672req/sec"`

which was causing just the cache bit to appear.
